// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHHq0e2B4n-RE_qMCN8zgJNVR63S5cNpM',
    appId: '1:496749797933:web:ac9eda0f0d7b96736d0ea4',
    messagingSenderId: '496749797933',
    projectId: 'battleships-2c10f',
    authDomain: 'battleships-2c10f.firebaseapp.com',
    storageBucket: 'battleships-2c10f.appspot.com',
    measurementId: 'G-H4YT1TK6ZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXoVCvHNbYZZv8PgyDPyfChgc3Sh8bkmQ',
    appId: '1:496749797933:android:7ee765c6d3f5abd16d0ea4',
    messagingSenderId: '496749797933',
    projectId: 'battleships-2c10f',
    storageBucket: 'battleships-2c10f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmQ3aAQNl_Q42LK6VXfezwpu2OlerCuwM',
    appId: '1:496749797933:ios:7c3456e0f8b4933e6d0ea4',
    messagingSenderId: '496749797933',
    projectId: 'battleships-2c10f',
    storageBucket: 'battleships-2c10f.appspot.com',
    iosBundleId: 'com.example.battleships',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmQ3aAQNl_Q42LK6VXfezwpu2OlerCuwM',
    appId: '1:496749797933:ios:7c3456e0f8b4933e6d0ea4',
    messagingSenderId: '496749797933',
    projectId: 'battleships-2c10f',
    storageBucket: 'battleships-2c10f.appspot.com',
    iosBundleId: 'com.example.battleships',
  );
}
